name: Test or Release

on:
  - push
  - pull_request

jobs:
  test-min:
    runs-on: ubuntu-latest
    name: With Node 10
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        registry-url: 'https://registry.npmjs.org'
    - name: Install PNPM
      uses: pnpm/action-setup@v2
      with:
        version: '5.x'
        run_install: |
          - args: [--frozen-lockfile, --no-verify-store-integrity]
    - name: Test
      run: npm test
  build-lts:
    needs: test-min
    runs-on: ubuntu-latest
    name: With Node LTS
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
        registry-url: 'https://registry.npmjs.org'
    - name: Install PNPM
      uses: pnpm/action-setup@v2
      with:
        version: '>=6'
        run_install: |
          - args: [--frozen-lockfile, --no-verify-store-integrity]
    - name: Test
      run: npm test
    - name: Publish
      uses: cycjimmy/semantic-release-action@v2
      with:
        semantic_version: 18
        branches: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
